import { WorkspaceLinks, ThemeGlyph } from './WorkspaceNavigation.jsx';
function MonthlyTrendChart({ monthly }) {
  const values = monthly.slice(-12); const width = 760; const height = 240; const pad = { top: 20, right: 24, bottom: 37, left: 28 }; const max = Math.max(...values.map(item => item.planned), 1); const step = (width - pad.left - pad.right) / Math.max(values.length, 1); const bar = Math.min(26, step * .28);
  const line = values.map((item, index) => `${index ? 'L' : 'M'} ${pad.left + step * index + step / 2} ${height - pad.bottom - item.score / 100 * (height - pad.top - pad.bottom)}`).join(' ');
  return <svg className="reference-chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Monthly planned and completed habit actions with completion score line"><defs><linearGradient id="tracker-month-line" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#7164d8"/><stop offset="1" stopColor="#aa9bed"/></linearGradient></defs>{[0,50,100].map(value => <line key={value} x1={pad.left} x2={width-pad.right} y1={height-pad.bottom-value/100*(height-pad.top-pad.bottom)} y2={height-pad.bottom-value/100*(height-pad.top-pad.bottom)} className="chart-grid"/>)}{values.map((item,index) => { const x = pad.left + step * index + step / 2; const plannedHeight = item.planned / max * (height-pad.top-pad.bottom); const completeHeight = item.completed / max * (height-pad.top-pad.bottom); return <g key={item.month}><rect x={x-bar-3} y={height-pad.bottom-plannedHeight} width={bar} height={plannedHeight} rx="4" className="bar-planned"><title>{`${item.month}: ${item.planned} planned actions`}</title></rect><rect x={x+3} y={height-pad.bottom-completeHeight} width={bar} height={completeHeight} rx="4" className="bar-complete"><title>{`${item.month}: ${item.completed} completed actions`}</title></rect><text x={x} y={height-11} textAnchor="middle">{new Date(`${item.month}-01T00:00:00`).toLocaleDateString('en-US',{month:'short'})}</text></g>; })}<path d={line} className="chart-line month-line"/><g className="chart-legend"><circle cx="20" cy="13" r="4" className="bar-planned"/><text x="29" y="17">Planned</text><circle cx="95" cy="13" r="4" className="bar-complete"/><text x="104" y="17">Completed</text><line x1="182" x2="196" y1="13" y2="13" className="chart-line month-line"/><text x="202" y="17">Score</text></g></svg>;
}

function CategoryComparisonChart({ series }) {
  const values = series.map(item => ({ ...item, points: item.points.slice(-30) })); const width = 760; const height = 240; const inset = 30; const days = Math.max(...values.map(item => item.points.length), 1); const palette = ['#b8892e','#858b92','#d4b260','#98938a','#c49b73','#a9b594'];
  const pathFor = points => { let started = false; return points.map((point, index) => { if (point.score === null) { started = false; return ''; } const x = inset + index * ((width-inset*2)/Math.max(days-1,1)); const y = height-inset-point.score/100*(height-inset*2); const command = started ? 'L' : 'M'; started = true; return `${command}${x} ${y}`; }).join(' '); };
  return <svg className="reference-chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Category completion comparison over time">{[0,50,100].map(value => <line key={value} x1={inset} x2={width-inset} y1={height-inset-value/100*(height-inset*2)} y2={height-inset-value/100*(height-inset*2)} className="chart-grid"/>)}{values.map((item,index) => <g key={item.category}><path d={pathFor(item.points.slice(-30))} fill="none" stroke={palette[index]} strokeWidth="3" strokeLinecap="round"><title>{item.category}</title></path>{item.points.slice(-30).map((point, pointIndex) => point.score === null ? null : <circle key={point.date} cx={inset + pointIndex * ((width-inset*2)/Math.max(days-1,1))} cy={height-inset-point.score/100*(height-inset*2)} r="4" fill={palette[index]}><title>{`${item.category} ${point.date}: ${point.score}%`}</title></circle>)}</g>)}<g className="chart-legend">{values.map((item,index) => <g key={item.category} transform={`translate(${index*130}, 0)`}><circle cx="18" cy="13" r="4" fill={palette[index]}/><text x="27" y="17">{item.category.toLowerCase()}</text></g>)}</g></svg>;
}

function VarianceChart({ variance }) {
  const values = variance.slice(-28); const width = 760; const height = 230; const pad = 28; const max = Math.max(...values.map(item => Math.abs(item.value)), 1); const center = height / 2; const step = (width-pad*2)/Math.max(values.length,1); const barWidth = Math.max(3,step*.6);
  return <svg className="reference-chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Daily completion variance against personal average"><line x1={pad} x2={width-pad} y1={center} y2={center} className="variance-zero"/>{values.map((item,index) => { const size = Math.abs(item.value)/max*(height/2-pad); const x = pad+step*index+(step-barWidth)/2; const positive = item.value >= 0; return <rect key={item.date} x={x} y={positive ? center-size : center} width={barWidth} height={size} rx="3" className={positive?'variance-positive':'variance-negative'}><title>{`${item.date}: ${item.value > 0 ? '+' : ''}${item.value} points vs average`}</title></rect>; })}<text x={pad} y={center-7}>Above average</text><text x={pad} y={center+15}>Below average</text></svg>;
}

export default function InsightsPage({ data, loading, error, dark, onBack, onTheme, onNavigate }) {
  const daily = data?.daily || [];
  const plotted = daily.slice(-60);
  const chartWidth = 860; const chartHeight = 245; const inset = 30;
  const points = plotted.map((day, index) => ({ x: inset + index * ((chartWidth - inset * 2) / Math.max(plotted.length - 1, 1)), y: chartHeight - inset - day.score / 100 * (chartHeight - inset * 2), ...day }));
  const line = points.map((point, index) => `${index ? 'L' : 'M'} ${point.x} ${point.y}`).join(' ');
  const area = points.length ? `${line} L ${points.at(-1).x} ${chartHeight - inset} L ${points[0].x} ${chartHeight - inset} Z` : '';
  const labelDate = value => new Date(`${value}T00:00:00`).toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
  return <main className={dark ? 'insights-page analytics-gold dark' : 'insights-page analytics-gold'}>
    <WorkspaceLinks active="Insights" onNavigate={onNavigate}/><header className="insights-header"><button className="back-button" onClick={onBack}>← Today</button><div><p className="eyebrow">TRACKER ANALYTICS · SAVED HISTORY ONLY</p><h1>Consistency, clearly seen<span>.</span></h1></div><button className="round-button" aria-label={`Switch to ${dark ? 'light' : 'dark'} mode`} onClick={onTheme}><ThemeGlyph dark={dark}/></button></header>
    {loading && <p className="insight-loading">Loading the records saved in MongoDB…</p>}
    {!loading && error && <section className="analytics-empty"><span>!</span><p className="eyebrow">ANALYTICS UNAVAILABLE</p><h2>The saved-history service could not be reached.</h2><p>{error}</p><button className="add-button" onClick={onBack}>Back to Today</button></section>}
    {!loading && !error && data?.empty && <section className="analytics-empty"><span>◌</span><p className="eyebrow">NO HISTORY YET</p><h2>Your first chart starts with your first completed routine.</h2><p>TRACKER will calculate this page from daily records only—never from sample data.</p><button className="add-button" onClick={onBack}>Add a routine</button></section>}
    {!loading && data && !data.empty && <><section className="insight-stats"><article><span>AVERAGE COMPLETION</span><strong>{data.summary.average}%</strong><small>across {data.summary.activeDays} active days</small></article><article><span>CURRENT STREAK</span><strong>{data.summary.currentStreak}<b> days</b></strong><small>fully completed days in a row</small></article><article><span>BEST STREAK</span><strong>{data.summary.bestStreak}<b> days</b></strong><small>your longest completed run</small></article></section>
      <section className="reference-grid"><article className="reference-card"><div className="chart-top"><div><p className="eyebrow">MONTHLY COMPLETION TREND</p><h2>Planned versus completed</h2></div><span>All saved months</span></div><MonthlyTrendChart monthly={data.monthly}/></article><article className="reference-card"><div className="chart-top"><div><p className="eyebrow">CATEGORY COMPARISON</p><h2>Habit areas over time</h2></div><span>Last 30 records</span></div><CategoryComparisonChart series={data.categorySeries}/></article></section>
      <section className="line-chart-section"><div className="chart-top"><div><p className="eyebrow">DAY-BY-DAY CONSISTENCY</p><h2>Your completion arc</h2></div><span>Since {labelDate(daily[0].date)}</span></div><svg className="consistency-chart" viewBox={`0 0 ${chartWidth} ${chartHeight}`} role="img" aria-label="Daily completion percentage since tracking began"><defs><linearGradient id="tracker-area" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#7164d8" stopOpacity=".38"/><stop offset="100%" stopColor="#7164d8" stopOpacity="0"/></linearGradient></defs>{[0,25,50,75,100].map(value => <g key={value}><line x1={inset} x2={chartWidth-inset} y1={chartHeight-inset-value/100*(chartHeight-inset*2)} y2={chartHeight-inset-value/100*(chartHeight-inset*2)} className="chart-grid"/><text x="0" y={chartHeight-inset-value/100*(chartHeight-inset*2)+4}>{value}%</text></g>)}<path d={area} fill="url(#tracker-area)"/><path d={line} className="chart-line"/>{points.filter((_, index) => index === 0 || index === points.length - 1 || index % Math.ceil(points.length / 5) === 0).map(point => <g key={point.date}><circle cx={point.x} cy={point.y} r="4" className="chart-dot"><title>{`${labelDate(point.date)}: ${point.score}%`}</title></circle><text x={point.x} y={chartHeight-6} textAnchor="middle">{labelDate(point.date)}</text></g>)}</svg></section>
      <section className="insight-grid"><article className="category-panel"><p className="eyebrow">ROUTINE KPIS</p><h2>Where your consistency lives</h2>{data.categories.map(item => <div className="category-row" key={item.category}><div><b>{item.category.toLowerCase()}</b><small>{item.routines} routine{item.routines === 1 ? '' : 's'}</small></div><div className="category-bar"><i style={{ width: `${item.score}%` }}/></div><strong>{item.score}%</strong></div>)}</article><article className="heatmap-panel"><p className="eyebrow">RECENT ACTIVITY</p><h2>Your commitment map</h2><div className="heatmap" aria-label="Last 84 days of completion history">{data.heatmap.map(day => <span key={day.date} className={!day.active ? 'heat-none' : day.score === 100 ? 'heat-full' : day.score >= 60 ? 'heat-high' : day.score > 0 ? 'heat-some' : 'heat-empty'} title={`${labelDate(day.date)}: ${day.active ? `${day.score}%` : 'No routines planned'}`}/>)}</div><div className="heat-legend"><span>Less</span><i className="heat-none"/><i className="heat-some"/><i className="heat-high"/><i className="heat-full"/><span>More</span></div></article></section>
      <section className="variance-card"><div className="chart-top"><div><p className="eyebrow">DAILY VARIANCE</p><h2>Above or below your own average</h2></div><span>Last 42 active days</span></div><VarianceChart variance={data.variance}/></section>
      <section className="habit-table"><div className="chart-top"><div><p className="eyebrow">HABIT LIBRARY</p><h2>Each routine, since day one</h2></div><span>{data.routines.length} tracked</span></div><div className="habit-table-head"><span>Routine</span><span>Area</span><span>Completion</span><span>Recorded days</span></div>{data.routines.map(routine => <div className="habit-table-row" key={routine.id}><b>{routine.title}</b><span className="habit-category">{routine.category}</span><span><i className="table-bar"><em style={{ width: `${routine.score}%` }}/></i>{routine.score}%</span><span>{routine.days}</span></div>)}</section>
    </>}
  </main>;
}
