import { useState } from 'react';
import { api, localDateKey } from './api.js';
const addDays = (date, amount) => { const value = new Date(`${date}T00:00:00`); value.setDate(value.getDate() + amount); return localDateKey(value); };
const mondayFor = date => { const value = new Date(`${date}T00:00:00`); const weekday = value.getDay(); return addDays(date, -(weekday === 0 ? 6 : weekday - 1)); };
export function WeekPlanner({ tasks, routines, token, onChanged, notify }) {
  const [weekStart, setWeekStart] = useState(mondayFor(localDateKey())); const days = Array.from({length:7},(_,index)=>addDays(weekStart,index));
  const move = async (taskId, scheduledDate) => { try { await api(`/tasks/${taskId}`, { token, method:'PATCH', body:{scheduledDate} }); await onChanged(); notify(`Moved to ${new Date(`${scheduledDate}T00:00:00`).toLocaleDateString([], {weekday:'long'})}`); } catch (error) { notify(error.message); } };
  const routineForDay = (routine, date) => { const day = new Date(`${date}T00:00:00`).getDay(); if (routine.status !== 'ACTIVE') return false; if (routine.frequency === 'WEEKDAYS') return day > 0 && day < 6; if (routine.frequency === 'WEEKENDS') return day === 0 || day === 6; if (routine.frequency === 'CUSTOM') return routine.scheduledDays.includes(day); return routine.frequency === 'DAILY'; };
  return <section className="week-planner"><header><button onClick={() => setWeekStart(addDays(weekStart,-7))}>← Previous week</button><div><p>TIMEBOXED WEEK</p><h2>{new Date(`${weekStart}T00:00:00`).toLocaleDateString([], {month:'short',day:'numeric'})} – {new Date(`${days[6]}T00:00:00`).toLocaleDateString([], {month:'short',day:'numeric'})}</h2></div><button onClick={() => setWeekStart(addDays(weekStart,7))}>Next week →</button></header><div className="week-columns">{days.map(date => { const dayTasks = tasks.filter(task => task.scheduledDate === date && !['ARCHIVED','DROPPED','DELEGATED'].includes(task.status)); const dayRoutines = routines.filter(routine => routineForDay(routine,date)); return <article key={date} className={date === localDateKey() ? 'today' : ''} onDragOver={event => event.preventDefault()} onDrop={event => move(event.dataTransfer.getData('text/task-id'),date)}><h3><span>{new Date(`${date}T00:00:00`).toLocaleDateString([], {weekday:'short'})}</span><b>{Number(date.slice(-2))}</b></h3>{dayTasks.map(task => <div draggable onDragStart={event => event.dataTransfer.setData('text/task-id',task._id)} className={`week-block ${task.itemType.toLowerCase()} ${task.status === 'COMPLETED' ? 'done' : ''}`} style={{'--block-size':`${Math.min(130,Math.max(48,Number(task.estimatedMinutes || 30)))}px`}} key={task._id}><span>{task.allDay ? 'ALL DAY' : task.startTime || task.deadline || 'FLEX'}</span><b>{task.title}</b><small>{task.estimatedMinutes || 30}m · drag to move</small></div>)}{dayRoutines.map(routine => <div className="week-block routine" key={routine._id}><span>{routine.preferredTime || 'ROUTINE'}</span><b>{routine.title}</b><small>{routine.estimatedMinutes || 25}m habit</small></div>)}{!dayTasks.length && !dayRoutines.length && <p className="week-open">Open space</p>}</article>; })}</div></section>;
}
